const DICT_CATS = [
  { id: "all",          label: "Todo" },
  { id: "saludos",      label: "Saludos" },
  { id: "orientacion",  label: "Orientacion" },
  { id: "transporte",   label: "Transporte" },
  { id: "comida",       label: "Comida" },
  { id: "numeros",      label: "Numeros" },
  { id: "emergencias",  label: "Emergencias" },
];

// es: español · pl: polaco · pron: pronunciación fonética en español
// pron: mayúsculas = sílaba tónica, guión = separación de sílabas
const DICT = [

  // ── SALUDOS ─────────────────────────────────────────────────────────────
  { cat: "saludos", emoji: "👋", es: "Hola (informal)",       pl: "Cześć",               pron: "CHESHCH" },
  { cat: "saludos", emoji: "🌅", es: "Buenos días",           pl: "Dzień dobry",          pron: "YIEN-dob-ri" },
  { cat: "saludos", emoji: "🌇", es: "Buenas tardes/noches",  pl: "Dobry wieczór",        pron: "DOB-ri VYIE-chur" },
  { cat: "saludos", emoji: "🌙", es: "Buenas noches",         pl: "Dobranoc",             pron: "dob-RA-nots" },
  { cat: "saludos", emoji: "🚪", es: "Adiós (formal)",        pl: "Do widzenia",          pron: "do-vid-ZE-nia" },
  { cat: "saludos", emoji: "✌️", es: "Adiós (informal)",      pl: "Cześć / Pa pa",        pron: "CHESHCH / pa-pa" },
  { cat: "saludos", emoji: "🙏", es: "Por favor",             pl: "Proszę",               pron: "PRO-she" },
  { cat: "saludos", emoji: "🤝", es: "Gracias",               pl: "Dziękuję",             pron: "yen-KU-ye" },
  { cat: "saludos", emoji: "😊", es: "De nada",               pl: "Nie ma za co",         pron: "nie-ma-ZA-tso" },
  { cat: "saludos", emoji: "😅", es: "Perdón / Disculpe",     pl: "Przepraszam",          pron: "pshe-PRA-sham" },
  { cat: "saludos", emoji: "✅", es: "Sí",                    pl: "Tak",                  pron: "tak" },
  { cat: "saludos", emoji: "❌", es: "No",                    pl: "Nie",                  pron: "nie" },
  { cat: "saludos", emoji: "🤷", es: "No entiendo",           pl: "Nie rozumiem",         pron: "nie-ro-ZU-miem" },
  { cat: "saludos", emoji: "🗣️", es: "¿Habla inglés?",       pl: "Czy mówi Pan po angielsku?", pron: "chi-MU-vi-pan-po-an-YIEL-sku" },
  { cat: "saludos", emoji: "🔁", es: "¿Puede repetirlo?",    pl: "Może Pan powtórzyć?",  pron: "MO-zhe-pan-pov-TU-zhich" },
  { cat: "saludos", emoji: "🐢", es: "Más despacio, por favor", pl: "Proszę mówić wolniej", pron: "PRO-she-MU-vich-VOL-niej" },
  { cat: "saludos", emoji: "😀", es: "¿Cómo estás?",         pl: "Jak się masz?",        pron: "yak-shie-MASH" },
  { cat: "saludos", emoji: "😌", es: "Bien, gracias",         pl: "Dobrze, dziękuję",     pron: "DOB-zhe YEN-ku-ye" },

  // ── ORIENTACION ─────────────────────────────────────────────────────────
  { cat: "orientacion", emoji: "❓", es: "¿Dónde está...?",    pl: "Gdzie jest...?",       pron: "GYIE-yest" },
  { cat: "orientacion", emoji: "⬅️", es: "A la izquierda",    pl: "W lewo",               pron: "v-LE-vo" },
  { cat: "orientacion", emoji: "➡️", es: "A la derecha",      pl: "W prawo",              pron: "v-PRA-vo" },
  { cat: "orientacion", emoji: "⬆️", es: "Todo recto",        pl: "Prosto",               pron: "PROS-to" },
  { cat: "orientacion", emoji: "📍", es: "Cerca",              pl: "Blisko",               pron: "BLIS-ko" },
  { cat: "orientacion", emoji: "🔭", es: "Lejos",              pl: "Daleko",               pron: "da-LE-ko" },
  { cat: "orientacion", emoji: "🏨", es: "Hotel",              pl: "Hotel",                pron: "HO-tel" },
  { cat: "orientacion", emoji: "🚽", es: "Baños / WC",         pl: "Toaleta",              pron: "to-a-LE-ta" },
  { cat: "orientacion", emoji: "🏛️", es: "Museo",             pl: "Muzeum",               pron: "mu-ZE-um" },
  { cat: "orientacion", emoji: "⛪", es: "Iglesia",            pl: "Kościół",              pron: "KOSH-chiuw" },
  { cat: "orientacion", emoji: "🏥", es: "Hospital",           pl: "Szpital",              pron: "SHPI-tal" },
  { cat: "orientacion", emoji: "💊", es: "Farmacia",           pl: "Apteka",               pron: "ap-TE-ka" },
  { cat: "orientacion", emoji: "🏧", es: "Cajero automático",  pl: "Bankomat",             pron: "ban-KO-mat" },
  { cat: "orientacion", emoji: "🏪", es: "Supermercado",       pl: "Supermarket",          pron: "su-per-MAR-ket" },
  { cat: "orientacion", emoji: "🗺️", es: "Mapa",             pl: "Mapa",                 pron: "MA-pa" },
  { cat: "orientacion", emoji: "🚶", es: "A pie / Andando",   pl: "Piechotą",             pron: "pie-HO-tom" },
  { cat: "orientacion", emoji: "🏙️", es: "Centro de la ciudad", pl: "Centrum",           pron: "TSEN-trum" },
  { cat: "orientacion", emoji: "🔒", es: "Cerrado",            pl: "Zamknięte",            pron: "zam-KNIEN-te" },
  { cat: "orientacion", emoji: "🔓", es: "Abierto",            pl: "Otwarte",              pron: "ot-VAR-te" },

  // ── TRANSPORTE ──────────────────────────────────────────────────────────
  { cat: "transporte", emoji: "🚂", es: "Estación de tren",   pl: "Dworzec kolejowy",     pron: "DVOR-zhets-ko-le-YO-vi" },
  { cat: "transporte", emoji: "🚌", es: "Estación de autobús", pl: "Dworzec autobusowy",  pron: "DVOR-zhets-aw-to-bu-SO-vi" },
  { cat: "transporte", emoji: "🚇", es: "Metro",              pl: "Metro",                pron: "ME-tro" },
  { cat: "transporte", emoji: "🚋", es: "Tranvía",            pl: "Tramwaj",              pron: "TRAM-vai" },
  { cat: "transporte", emoji: "🚕", es: "Taxi",               pl: "Taksówka",             pron: "tak-SUF-ka" },
  { cat: "transporte", emoji: "✈️", es: "Aeropuerto",         pl: "Lotnisko",             pron: "lot-NIS-ko" },
  { cat: "transporte", emoji: "🎫", es: "Billete / Ticket",   pl: "Bilet",                pron: "BI-let" },
  { cat: "transporte", emoji: "💰", es: "¿Cuánto cuesta?",    pl: "Ile kosztuje?",        pron: "I-le-kosh-TU-ye" },
  { cat: "transporte", emoji: "🕐", es: "¿A qué hora sale?",  pl: "O której odjeżdża?",   pron: "o-KTU-rei-od-YEZH-ja" },
  { cat: "transporte", emoji: "📅", es: "Hoy",                pl: "Dzisiaj",              pron: "JI-shai" },
  { cat: "transporte", emoji: "⏰", es: "Mañana",             pl: "Jutro",                pron: "YU-tro" },
  { cat: "transporte", emoji: "🛑", es: "Parada",             pl: "Przystanek",           pron: "pshi-STA-nek" },
  { cat: "transporte", emoji: "🔢", es: "¿Cuántas paradas?",  pl: "Ile przystanków?",     pron: "I-le-pshi-STAN-kuf" },
  { cat: "transporte", emoji: "🏁", es: "Llegada",            pl: "Przyjazd",             pron: "PSHi-yazd" },
  { cat: "transporte", emoji: "🚦", es: "Salida",             pl: "Wyjazd / Odjazd",      pron: "VI-yazd / OD-yazd" },

  // ── COMIDA ──────────────────────────────────────────────────────────────
  { cat: "comida", emoji: "💧", es: "Agua (sin gas)",          pl: "Woda niegazowana",     pron: "VO-da-nie-ga-ZO-va-na" },
  { cat: "comida", emoji: "🫧", es: "Agua con gas",            pl: "Woda gazowana",        pron: "VO-da-ga-ZO-va-na" },
  { cat: "comida", emoji: "🍺", es: "Cerveza",                 pl: "Piwo",                 pron: "PI-vo" },
  { cat: "comida", emoji: "🍷", es: "Vino",                    pl: "Wino",                 pron: "VI-no" },
  { cat: "comida", emoji: "☕", es: "Café",                    pl: "Kawa",                 pron: "KA-va" },
  { cat: "comida", emoji: "🫖", es: "Té",                      pl: "Herbata",              pron: "her-BA-ta" },
  { cat: "comida", emoji: "🍞", es: "Pan",                     pl: "Chleb",                pron: "hleb" },
  { cat: "comida", emoji: "🥩", es: "Carne",                   pl: "Mięso",                pron: "MIEN-so" },
  { cat: "comida", emoji: "🐷", es: "Cerdo",                   pl: "Wieprzowina",          pron: "viep-sho-VI-na" },
  { cat: "comida", emoji: "🥗", es: "Sin carne / Vegetariano", pl: "Bez mięsa",           pron: "bez-MIEN-sa" },
  { cat: "comida", emoji: "🥟", es: "Pierogi (empanadillas)",  pl: "Pierogi",              pron: "pie-RO-gi" },
  { cat: "comida", emoji: "🥣", es: "Sopa de remolacha (típica)", pl: "Barszcz",          pron: "BARSHCH" },
  { cat: "comida", emoji: "🧆", es: "Albóndiga (típico)",      pl: "Kotlet mielony",       pron: "KOT-let-mie-LO-ni" },
  { cat: "comida", emoji: "🧂", es: "Sal / Sin sal",           pl: "Sól / Bez soli",       pron: "sul / bez-SO-li" },
  { cat: "comida", emoji: "🤧", es: "Soy alérgico a...",       pl: "Jestem uczulony na...", pron: "YES-tem-u-chu-LO-ni-na" },
  { cat: "comida", emoji: "🧾", es: "La cuenta, por favor",   pl: "Rachunek, proszę",     pron: "ra-HU-nek-PRO-she" },
  { cat: "comida", emoji: "🥂", es: "¡Salud!",                 pl: "Na zdrowie!",          pron: "na-ZDRO-vie" },
  { cat: "comida", emoji: "🍽️", es: "Restaurante",            pl: "Restauracja",          pron: "res-taw-RA-tsya" },
  { cat: "comida", emoji: "🌅", es: "Desayuno",                pl: "Śniadanie",            pron: "shnia-DA-nie" },
  { cat: "comida", emoji: "☀️", es: "Almuerzo / Comida",       pl: "Obiad",                pron: "OB-yad" },
  { cat: "comida", emoji: "🌙", es: "Cena",                    pl: "Kolacja",              pron: "ko-LA-tsya" },
  { cat: "comida", emoji: "📌", es: "Mesa para dos",           pl: "Stolik dla dwóch",     pron: "STO-lik-dla-DVUH" },

  // ── NUMEROS ─────────────────────────────────────────────────────────────
  { cat: "numeros", emoji: "0️⃣", es: "Cero — 0",   pl: "Zero",          pron: "ZE-ro" },
  { cat: "numeros", emoji: "1️⃣", es: "Uno — 1",    pl: "Jeden",         pron: "YE-den" },
  { cat: "numeros", emoji: "2️⃣", es: "Dos — 2",    pl: "Dwa",           pron: "dva" },
  { cat: "numeros", emoji: "3️⃣", es: "Tres — 3",   pl: "Trzy",          pron: "tshi" },
  { cat: "numeros", emoji: "4️⃣", es: "Cuatro — 4", pl: "Cztery",        pron: "CHTE-ri" },
  { cat: "numeros", emoji: "5️⃣", es: "Cinco — 5",  pl: "Pięć",          pron: "pienCH" },
  { cat: "numeros", emoji: "6️⃣", es: "Seis — 6",   pl: "Sześć",         pron: "sheshCH" },
  { cat: "numeros", emoji: "7️⃣", es: "Siete — 7",  pl: "Siedem",        pron: "SHE-dem" },
  { cat: "numeros", emoji: "8️⃣", es: "Ocho — 8",   pl: "Osiem",         pron: "O-shem" },
  { cat: "numeros", emoji: "9️⃣", es: "Nueve — 9",  pl: "Dziewięć",      pron: "yie-VIENICH" },
  { cat: "numeros", emoji: "🔟", es: "Diez — 10",   pl: "Dziesięć",      pron: "YIE-shenich" },
  { cat: "numeros", emoji: "🔢", es: "Once — 11",   pl: "Jedenaście",    pron: "ye-de-NASH-chie" },
  { cat: "numeros", emoji: "🔢", es: "Doce — 12",   pl: "Dwanaście",     pron: "dva-NASH-chie" },
  { cat: "numeros", emoji: "🔢", es: "Veinte — 20", pl: "Dwadzieścia",   pron: "dva-YESH-cha" },
  { cat: "numeros", emoji: "🔢", es: "Treinta — 30", pl: "Trzydzieści", pron: "tshi-YESH-chi" },
  { cat: "numeros", emoji: "🔢", es: "Cincuenta — 50", pl: "Pięćdziesiąt", pron: "pien-YIE-shomt" },
  { cat: "numeros", emoji: "💯", es: "Cien — 100",  pl: "Sto",           pron: "sto" },
  { cat: "numeros", emoji: "🔢", es: "Doscientos — 200", pl: "Dwieście", pron: "DYESH-chie" },
  { cat: "numeros", emoji: "🔢", es: "Quinientos — 500", pl: "Pięćset", pron: "PIEN-set" },
  { cat: "numeros", emoji: "💰", es: "Mil — 1000",   pl: "Tysiąc",       pron: "TI-shonts" },
  { cat: "numeros", emoji: "💲", es: "Esloti (moneda)", pl: "Złoty (PLN)", pron: "ZWO-ti" },
  { cat: "numeros", emoji: "💸", es: "Grosz (centavo)", pl: "Grosz",     pron: "grosh" },

  // ── EMERGENCIAS ─────────────────────────────────────────────────────────
  { cat: "emergencias", emoji: "🆘", es: "¡Socorro! ¡Ayuda!",    pl: "Pomocy!",              pron: "po-MO-tsi" },
  { cat: "emergencias", emoji: "🚨", es: "¡Llama a la policía!", pl: "Proszę zadzwonić na policję!", pron: "PRO-she-za-DZVO-nitch-na-po-LI-tsie" },
  { cat: "emergencias", emoji: "🚑", es: "¡Llama a una ambulancia!", pl: "Proszę wezwać pogotowie!", pron: "PRO-she-VEZ-vach-po-go-TO-vie" },
  { cat: "emergencias", emoji: "🔥", es: "¡Fuego! ¡Incendio!",   pl: "Pożar!",               pron: "PO-zhar" },
  { cat: "emergencias", emoji: "👨‍⚕️", es: "Necesito un médico",  pl: "Potrzebuję lekarza",   pron: "pot-she-BU-ye-le-KA-zha" },
  { cat: "emergencias", emoji: "💊", es: "Necesito medicamento", pl: "Potrzebuję lekarstwa", pron: "pot-she-BU-ye-le-KARS-tva" },
  { cat: "emergencias", emoji: "🤒", es: "Estoy enfermo/a",      pl: "Jestem chory / chora", pron: "YES-tem-HO-ri / HO-ra" },
  { cat: "emergencias", emoji: "🤕", es: "Me duele aquí",        pl: "Boli mnie tutaj",      pron: "BO-li-MNIE-tu-tai" },
  { cat: "emergencias", emoji: "👜", es: "Me han robado",        pl: "Okradziono mnie",      pron: "ok-ra-YO-no-MNIE" },
  { cat: "emergencias", emoji: "🔑", es: "He perdido mis llaves", pl: "Zgubiłem klucze",     pron: "zgu-BI-wem-KLU-che" },
  { cat: "emergencias", emoji: "🗺️", es: "Estoy perdido/a",     pl: "Zgubiłem się / Zgubiłam się", pron: "zgu-BI-wem-SHIE / zgu-BI-wam-SHIE" },
  { cat: "emergencias", emoji: "📋", es: "Necesito ir a urgencias", pl: "Potrzebuję iść na izbę przyjęć", pron: "pot-she-BU-ye-ish-na-IZ-be-PSHi-yench" },
  { cat: "emergencias", emoji: "🚔", es: "Policía",               pl: "Policja",              pron: "po-LI-tsya" },
  { cat: "emergencias", emoji: "🚒", es: "Bomberos",              pl: "Straż pożarna",        pron: "strash-po-ZHAR-na" },
  { cat: "emergencias", emoji: "🇪🇺", es: "Emergencias (Europa)", pl: "112",                 pron: "sto-dwanas-cie" },
  { cat: "emergencias", emoji: "👮", es: "Policía (directo)",     pl: "997",                  pron: "dziewięćset dziewięćdziesiąt siedem" },
  { cat: "emergencias", emoji: "🚑", es: "Ambulancia (directo)",  pl: "999",                  pron: "dziewięćset dziewięćdziesiąt dziewięć" },
];
