const REST_CITY_FILTERS = [
  { id: "all",      label: "Todos" },
  { id: "cracovia", label: "Cracovia" },
  { id: "varsovia", label: "Varsovia" },
  { id: "gdansk",   label: "Gdansk" },
];

const REST_COLOR = "#e67e22";

const RESTAURANTS = [

  // ── CRACOVIA ─────────────────────────────────────────────────────────────
  {
    id: "kr-euskadi",
    city: "cracovia",
    cityLabel: "Cracovia · Stare Podgórze",
    name: "Euskadi – Kuchnia Baskijska",
    type: "Cocina vasca · Guía Michelin",
    icon: "🦑",
    price: "€€",
    lat: 50.0495,
    lng: 19.9494,
    description: "El mejor restaurante español de toda Polonia según críticos gastronómicos. Figura en la Guía Michelin con distinción de 'Buena Cocina'. Cocina vasca auténtica en un local pequeño de unas 12 mesas, ambiente industrial sin pretensiones. Regentado con espíritu genuinamente vasco.",
    order: [
      "Pulpo a la gallega — con pimentón y aceite de oliva",
      "Croquetas de jamón ibérico",
      "Gambas al ajillo",
      "Pimientos de Padrón",
      "Pintxos variados en la barra",
      "Txakoli (vino blanco vasco)",
    ],
    practical: {
      direccion: "ul. Kazimierza Brodzińskiego 4/U1, Stare Podgórze",
      horario: "Dom–Jue 12:00–22:00 · Vie–Sáb 12:00–22:30",
      precio: "€€ · ~70–110 PLN por persona",
      reserva: "Imprescindible reservar, especialmente fines de semana",
    },
    links: {
      web: "https://www.euskadi.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274772-d12209748-Reviews-Euskadi_Kuchnia_Baskijska-Krakow_Lesser_Poland_Province_Southern_Poland.html",
    }
  },
  {
    id: "kr-arriva",
    city: "cracovia",
    cityLabel: "Cracovia · Podgórze",
    name: "¡Arriva! Tapas & Pintxos",
    type: "Tapas y pintxos contemporáneos",
    icon: "🍢",
    price: "€€",
    lat: 50.0479,
    lng: 19.9583,
    description: "Abierto en 2023, ha ganado rápidamente reputación. Cocina ibérica regional con pintxos al estilo de San Sebastián, paella vegana, tarta de queso vasca y sangría de temporada. Ambiente animado, bueno para grupos. Disponible también en Bolt Food y Wolt.",
    order: [
      "Selección de pintxos de temporada",
      "Tarta de queso vasca (Basque cheesecake)",
      "Empanadas",
      "Paella vegana",
      "Sangría de temporada",
    ],
    practical: {
      direccion: "ul. Podgórska 34, Podgórze",
      horario: "Lun 12:00–21:00 · Mar–Sáb 12:00–23:00 · Dom 12:00–21:00",
      precio: "€€ · ~60–90 PLN por persona",
      reserva: "Recomendable en fin de semana (Zjedz.my)",
    },
    links: {
      web: null,
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274772-d28674013-Reviews-Arriva_Krakow-Krakow_Lesser_Poland_Province_Southern_Poland.html",
    }
  },
  {
    id: "kr-alejos",
    city: "cracovia",
    cityLabel: "Cracovia · Casco Antiguo",
    name: "Alejo's Tapas Grill & Wine",
    type: "Tapas y parrilla hispano-americana · Certificado Embajada",
    icon: "🥩",
    price: "€€",
    lat: 50.0629,
    lng: 19.9399,
    description: "Certificado por el programa Foods & Wines from Spain de la Embajada española — uno de los pocos en toda Polonia. Fusiona tradición española con grill sudamericano. Cocina abierta a la vista del cliente. Ubicación ideal en el Casco Antiguo.",
    order: [
      "Tabla de tapas mixtas para empezar",
      "Pulpo a la parrilla",
      "Txuleta — chuleta de vaca al estilo vasco",
      "Jamón ibérico cortado a cuchillo",
      "Paella",
    ],
    practical: {
      direccion: "ul. św. Filipa 16, Casco Antiguo",
      horario: "Consultar en Google Maps (horario variable)",
      precio: "€€ · ~100–120 PLN por persona",
      tip: "La ubicación en el Casco Antiguo lo hace muy accesible combinando con el Mercado Central",
    },
    links: {
      web: "https://alejostapas.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274772-d23822091-Reviews-Alejo_s_Tapas_Grill_Wine-Krakow_Lesser_Poland_Province_Southern_Poland.html",
    }
  },
  {
    id: "kr-manana",
    city: "cracovia",
    cityLabel: "Cracovia · Kleparz",
    name: "Mañana",
    type: "Tapas y bar de vinos naturales",
    icon: "🍷",
    price: "€€–€€€",
    lat: 50.0680,
    lng: 19.9441,
    description: "El favorito de los locales, algo alejado del circuito turístico. Más íntimo y centrado en los vinos naturales que en el volumen. Valorado con 4,6/5 en más de 940 reseñas. Tiene fama de servir algunas de las mejores tapas que se pueden comer en toda Polonia.",
    order: [
      "Empanadas",
      "Patatas bravas",
      "Croquetas",
      "Paella",
      "Selección de vinos naturales españoles",
    ],
    practical: {
      direccion: "ul. Kurkowa 1, Kleparz (junto a la estación de tren)",
      horario: "Mie–Jue 16:00–21:00 · Vie–Sáb 12:00–22:00 · Dom 12:00–20:00 · Lun–Mar CERRADO",
      precio: "€€–€€€ · ~160–180 PLN por persona",
      tip: "Ambiente de tarde-noche, más bar de vinos que restaurante. Ideal para una copa larga con tapas",
    },
    links: {
      web: null,
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274772-d17513212-Reviews-Manana-Krakow_Lesser_Poland_Province_Southern_Poland.html",
    }
  },

  // ── VARSOVIA ─────────────────────────────────────────────────────────────
  {
    id: "wa-bilbao",
    city: "varsovia",
    cityLabel: "Varsovia · Śródmieście",
    name: "Bilbao – Pintxos, Wine, Music",
    type: "Bar de pintxos vascos · Certificado Embajada · Música en vivo",
    icon: "🎸",
    price: "€€",
    lat: 52.2213,
    lng: 21.0178,
    description: "Uno de los 7 únicos restaurantes en Polonia certificados por la Embajada de España. Abierto en 2022, inspirado directamente en la cultura de bares de Bilbao y el País Vasco. Pintxos auténticos, ambiente muy animado, noches con música en vivo. Top 300 en TripAdvisor Varsovia de más de 3.000 restaurantes.",
    order: [
      "Selección completa de pintxos",
      "Txuleta — chuletón de vaca al estilo vasco",
      "Tabla de embutidos y quesos españoles",
      "Txakoli por copas",
      "Vinos españoles de la carta",
    ],
    practical: {
      direccion: "ul. Koszykowa 55, Śródmieście",
      horario: "Lun 12:00–21:00 · Mar–Vie 13:00–00:00 · Sáb–Dom 16:00–00:00",
      precio: "€€ · ~90–130 PLN por persona",
      reserva: "Muy recomendable en fin de semana",
    },
    links: {
      web: "https://bilbao.com.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274856-d24084550-Reviews-Bilbao_Pintxos_Wine_Tapas-Warsaw_Mazovia_Province_Central_Poland.html",
    }
  },
  {
    id: "wa-trestoros",
    city: "varsovia",
    cityLabel: "Varsovia · Powiśle",
    name: "Tres Toros",
    type: "Bistró español · Mariscos y pulpo gallego",
    icon: "🐙",
    price: "€€–€€€",
    lat: 52.2360,
    lng: 21.0303,
    description: "Uno de los pocos restaurantes de Varsovia que tiene el pulpo a la gallega explícitamente en su carta. Situado en Elektrownia Powiśle — una central eléctrica histórica reconvertida en complejo gastronómico. Ambiente elegante, carnes orgánicas y marisco fresco. También certificado por Foods & Wines from Spain.",
    order: [
      "Pulpo a la gallega — su plato estrella",
      "Patatas bravas",
      "Croquetas de jamón",
      "Pimientos de Padrón",
      "Chorizo al vino",
      "Secreto ibérico a la parrilla",
    ],
    practical: {
      direccion: "ul. Dobra 40 (Elektrownia Powiśle), Powiśle",
      horario: "Consultar en su web o Google Maps",
      precio: "€€–€€€ · ~120–160 PLN por persona",
      reserva: "Recomendable. Reservas: +48 666 555 765",
      tip: "El complejo Elektrownia Powiśle merece la visita por sí solo — ideal para una noche completa",
    },
    links: {
      web: "https://trestoros.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274856-d21178461-Reviews-Tres_Toros-Warsaw_Mazovia_Province_Central_Poland.html",
    }
  },
  {
    id: "wa-pablos",
    city: "varsovia",
    cityLabel: "Varsovia · Wola",
    name: "Pablo's Tapas Gastrobar",
    type: "Tapas gastrobar auténtico",
    icon: "🫒",
    price: "€",
    lat: 52.2375,
    lng: 20.9972,
    description: "Fundado por Pablo Martín Delgado, español que trajo los sabores de su infancia a Varsovia. Más de 30 tapas auténticas que representan varias regiones de España. La opción más asequible y auténtica de la ciudad. Valorado 4,4/5 en TripAdvisor.",
    order: [
      "Patatas bravas",
      "Croquetas caseras",
      "Gambas al ajillo",
      "Tortilla española",
      "Calamares a la plancha",
      "Paella",
    ],
    practical: {
      direccion: "ul. Grzybowska 5a, Wola",
      horario: "Consultar en Google Maps",
      precio: "€ · ~60–80 PLN por persona",
      tip: "El más económico con cocina auténtica española. Perfecto para comer bien sin gastar mucho",
    },
    links: {
      web: "https://tapasgastrobar.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274856-d28144742-Reviews-Pablo_s_Tapas_Gastrobar-Warsaw_Mazovia_Province_Central_Poland.html",
    }
  },
  {
    id: "wa-solysom",
    city: "varsovia",
    cityLabel: "Varsovia · Śródmieście",
    name: "Sol y Sombra Tapas Bar",
    type: "Bar de tapas clásico",
    icon: "☀️",
    price: "€–€€",
    lat: 52.2389,
    lng: 20.9963,
    description: "Una institución en Varsovia para las tapas, con años de experiencia. Ambiente de barrio, admite mascotas, noches con música en vivo. Más orientado a copas con tapas que a cena formal. Amplia carta de sangrías.",
    order: [
      "Tortilla española",
      "Patatas bravas",
      "Tapas de marisco fresco",
      "Croquetas",
      "Aceitunas aliñadas",
      "Sangría de la casa",
    ],
    practical: {
      direccion: "ul. Grzybowska 2/16, Śródmieście",
      horario: "Lun 11:00–21:00 · Mar–Sáb 11:00–23:00",
      precio: "€–€€ · ~60–90 PLN por persona",
      tip: "Ideal para tapear y tomar algo, no tanto para cena formal. Ambiente muy relajado",
    },
    links: {
      web: "https://solysombra.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274856-d3775725-Reviews-Sol_y_Sombra-Warsaw_Mazovia_Province_Central_Poland.html",
    }
  },
  {
    id: "wa-latienda",
    city: "varsovia",
    cityLabel: "Varsovia · Wola / Ochota",
    name: "La Tienda Española",
    type: "Tapas bar + Delicatessen español",
    icon: "🥩",
    price: "€€",
    lat: 52.2095,
    lng: 20.9779,
    description: "Mitad bar de tapas, mitad deli español con productos artesanos importados directamente de pequeños productores: quesos, aceites, aceitunas, jamón ibérico y vinos. Regentado por Miguel (español, maestro jamonero) y Marzena. Experiencia única y boutique.",
    order: [
      "Jamón ibérico de bellota cortado a mano en la barra",
      "Pintxos variados",
      "Quesos artesanos españoles",
      "Setas a la plancha",
      "Gambas a la plancha",
    ],
    practical: {
      direccion: "ul. Posąg 7 Panien 20, Wola/Ochota",
      horario: "Mar–Dom 12:00–22:00",
      precio: "€€ · ~80–120 PLN por persona",
      tip: "También venden productos para llevar a casa. Imprescindible si eres fan del jamón ibérico",
    },
    links: {
      web: null,
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274856-d25186588-Reviews-La_Tienda_Espanola-Warsaw_Mazovia_Province_Central_Poland.html",
    }
  },

  // ── GDANSK ───────────────────────────────────────────────────────────────
  {
    id: "gd-horaespana",
    city: "gdansk",
    cityLabel: "Gdansk · Frente al mar",
    name: "Hora de España",
    type: "Restaurante español completo · Mariscos y tapas",
    icon: "🦞",
    price: "€€",
    lat: 54.3521,
    lng: 18.6466,
    description: "El mejor restaurante español del norte de Polonia. Más de 3.250 reseñas, de las cuales 2.564 son 5 estrellas. Tiene dos salas en la misma dirección (Hora de España 1.0 y 2.0). La referencia absoluta en Pomerania para la cocina española. Menú muy orientado al mar, lo más parecido a cocina gallega de los tres.",
    order: [
      "Tapas de jamón con tomate",
      "Pulpo con papas y pimentón",
      "Sopa de mariscos",
      "Pasta negra con tinta de calamar y gambas",
      "Paella",
      "Pimientos de Padrón",
    ],
    practical: {
      direccion: "ul. Wały Jagiellońskie 28/30, Śródmieście",
      horario: "Lun–Jue 11:00–23:00 · Vie–Sáb 11:00–00:00 · Dom 11:00–22:00",
      precio: "€€ · Tapas 24–49 PLN (~5–11€)",
      reserva: "Muy recomendable, especialmente fines de semana",
    },
    links: {
      web: "https://horadeespana.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274725-d23444065-Reviews-Hora_De_Espana-Gdansk_Pomerania_Province_Northern_Poland.html",
    }
  },
  {
    id: "gd-patio",
    city: "gdansk",
    cityLabel: "Gdansk · Casco Antiguo",
    name: "Patio Español",
    type: "Taberna andaluza · Paella y tapas",
    icon: "🥘",
    price: "€",
    lat: 54.3490,
    lng: 18.6528,
    description: "Uno de los restaurantes españoles más antiguos de Gdansk. Decoración de taberna andaluza, más de 4.000 reseñas con 4,4/5. Excelente relación calidad-precio: tapas calientes para dos a 48 PLN, paella mixta para dos a 78 PLN. Muy popular entre los locales, apartado del ruido turístico principal.",
    order: [
      "Tabla de tapas mixtas (48 PLN para dos)",
      "Paella mixta ternera + gambas (78 PLN para dos)",
      "Croquetas",
      "Patatas bravas",
      "Sangría de la casa",
    ],
    practical: {
      direccion: "ul. Tandeta 1 (entrada desde ul. Szeroka), Casco Antiguo",
      horario: "Lun–Jue 12:00–23:00 · Vie–Sáb 12:00–00:00 · Dom 12:00–22:00",
      precio: "€ · ~50–70 PLN por persona (el más económico de Gdansk)",
      tip: "Está algo escondido — búscalo activamente, merece la pena. Perfecto para familias",
    },
    links: {
      web: "https://patioespanol.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274725-d4476235-Reviews-Restauracja_Patio_Espanol-Gdansk_Pomerania_Province_Northern_Poland.html",
    }
  },
  {
    id: "gd-holatapas",
    city: "gdansk",
    cityLabel: "Gdansk · Calle Piwna (junto a Sta. María)",
    name: "Hola Tapas",
    type: "Tapas bar + Microcervecería propia",
    icon: "🍺",
    price: "€€",
    lat: 54.3494,
    lng: 18.6521,
    description: "Valorado 4,8/5 sobre casi 4.000 reseñas — el mejor valorado de Gdansk. Tiene microcervecería propia en el local. Mezcla cocina española con toques mexicanos. Situada en la calle Piwna (calle de la Cerveza), junto a la Basílica de Santa María. El más animado y social de los tres.",
    order: [
      "Aceitunas y tabla de quesos españoles",
      "Patatas bravas",
      "Croquetas",
      "Chorizo a la plancha",
      "Pimientos de Padrón",
      "Cervezas artesanas de la microcervecería propia",
    ],
    practical: {
      direccion: "ul. Piwna 50/51, Casco Antiguo (junto a Basílica de Sta. María)",
      horario: "Diario desde mediodía",
      precio: "€€ · ~70–100 PLN por persona",
      tip: "Combínalo con la visita a la Basílica de Santa María. La calle Piwna es peatonal y muy animada por las noches",
    },
    links: {
      web: "https://holatapas.pl/",
      ta:  "https://www.tripadvisor.com/Restaurant_Review-g274725-d20257332-Reviews-Hola_Tapas-Gdansk_Pomerania_Province_Northern_Poland.html",
    }
  },
];
